######################################################################
# Automatically generated by qmake (2.01a) Fr. Mai 20 14:23:21 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LaserCommanderMainWindow.h
SOURCES += LaserCommanderMainWindow.cc Testing.cc
