
AngleOfCameraFrameInRefFrame_dA:
	@mkdir -p bin
	g++ AngleOfCameraFrameInRefFrame_dA.cc -o bin/AngleOfCameraFrameInRefFrame_dA `root-config --glibs --cflags`

all:
	AngleOfCameraFrameInRefFrame_dA

clean:
	rm -rf bin/
